### ISSUE TITLE
jiji.com

### ISSUE THREAD

**Issue by stm-x** [eEIi0A5L/adblock_filter#15]
**Issue**
Using fix filter with AdGuard causes problems with jiji.com
See here for details.
https://github.com/AdguardTeam/AdguardFilters/issues/45369

**Comment by stm-x** [comment]
Test Link:`https://www.jiji.com/jc/article?k=2021101400933&g=eco&utm_source=top&utm_medium=topics&utm_campaign=edit`

**Comment by eEIi0A5L** [comment]
Thanks for a report.
I restricted a filter from:
@@_campaign=$document,first-party
to
@@_campaign=$document,first-party,domain=shopping.google.com

It will be no affected to www.jiji.com.
