### ISSUE TITLE
:upwardをAdGuard互換に

### ISSUE THREAD

**Issue by Yuki2718** [eEIi0A5L/adblock_filter#8]
ある環境でAdGuardブラウザ拡張機能にもちフィルタを導入させていただいているのですが、`:upward`が機能しません。
一番簡単な対処は
```
!#if adguard
www.yahoo.co.jp#?#img[alt="いい買物の日"][src^="https://s.yimg.jp/images/evt/kaimono/"]:nth-ancestor(1)
!#endif
```
のように?を入れてnth-ancestorに置き換えたルールを追加することだと思います。ただ、処理効率の点からいうと元のルールを`:has`などに置き換えたほうがいいかもしれません。

**Comment by krystian3w** [comment]
> you should add `?` after first `#`
 
Upward works without `#?#` also CoreLibs/tsurlfilter should add this itself to compatibility with older ExtendedCSS AdGuard rules.

**Comment by S4Y78C9S** [comment]
thanks for info!

**Comment by eEIi0A5L** [comment]
Thanks for info!

**Comment by Yuki2718** [comment]
> > you should add `?` after first `#`
> 
> Upward works without `#?#` also CoreLibs/tsurlfilter should add this itself to compatibility with older ExtendedCSS AdGuard rules.

Sure it works, in fact AG auto-converts most of rules yet Alex once advised to add `?` regardless. Anyway these rules were removed as `:upward()` became fully compatible, except that on AG it must be trailing operator.
